//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group5__iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AboutUs
    {
        [Display(Name = "Brick-and-mortar location")]
        [DataType(DataType.PostalCode)]
        public string companyAddress { get; set; }

        [Display(Name = "Shipping policy")]
        public string companyShippingPolicy { get; set; }

        [Display(Name = "Return policy")]
        public string companyReturnPolicy { get; set; }

        [Display(Name = "Contact")]
        public string companyContactInfo { get; set; }

        [Display(Name = "About us")]
        public string companyBusinessDescription { get; set; }
        public string adminID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
