//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group5__iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cataloging
    {
        public string departmentID { get; set; }
        public string categoryID { get; set; }
        public string productID { get; set; }

        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Product Product { get; set; }
    }
}
