//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group5__iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Email = new HashSet<Email>();
            this.ItemDelivery = new HashSet<ItemDelivery>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.UserComments = new HashSet<UserComments>();
            this.UserQuery = new HashSet<UserQuery>();
        }
        [Required(ErrorMessage = "ID required")]
        [Display(Name = "ID")]
        public string customerID { get; set; }

        [Required(ErrorMessage = "Name required")]
        [Display(Name = "Name")]
        public string customerName { get; set; }

        [Required(ErrorMessage = "Shipping Address required")]
        [Display(Name = "Shipping Address")]
        public string customerShippingAddress { get; set; }

        [Required(ErrorMessage = "Billing Address required")]
        [Display(Name = "Billing Address")]
        public string customerBillingAddress { get; set; }

        [Required(ErrorMessage = "Birthdate required")]
        [Display(Name = "Birthdate")]
        [DataType(DataType.DateTime)]
        public System.DateTime customerDOB { get; set; }

        [Display(Name = "Gender")]
        public string customerGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDelivery> ItemDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComments> UserComments { get; set; }
        public virtual UserPassword UserPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuery> UserQuery { get; set; }
    }
}
