//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group5__iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Department
    {
        [StringLength(10, MinimumLength = 10, ErrorMessage = "ID must be 10 characters.")]
        [Required(ErrorMessage = "ID required")]
        [Display(Name = "ID")]
        [Index(IsUnique = true)]
        public string departmentID { get; set; }

        [StringLength(50, ErrorMessage = "Max length of name is 50 characters.")]
        [Required(ErrorMessage = "Name required")]
        [Display(Name = "Name")]
        public string departmentName { get; set; }

        [Display(Name = "Description")]
        public string departmentDescription { get; set; }
    
        public virtual Cataloging Cataloging { get; set; }
    }
}
