//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group5__iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserQuery
    {
        [Required(ErrorMessage ="Query # required")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Query # must be 10 characters.")]
        [Display(Name="Query #")]
        [Index(IsUnique = true)]
        public string queryNo { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.DateTime)]
        public System.DateTime queryDate { get; set; }
        [Required(ErrorMessage = "Message required")]
        [Display(Name = "Message")]
        public string queryDescription { get; set; }
        [Required(ErrorMessage = "Customer required")]
        [Display(Name = "Customer")]
        public string customerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
